### ISSUE TITLE
3.5.2.3 Sending Telemetry Update and the delete field

### ISSUE THREAD

**Issue by gwizdms** [openconfig/gnmi#145]
Interpretations in regards to 3.5.2.3 and the delete field have led to opposing discussions on its use.  The question... does the delete field use only apply to mode ON_CHANGE or is it subscription mode independent?  Our interpretation is the delete field should apply to both SAMPLE and ON_CHANGE and be subscription mode independent.  Without an implicit end to a SAMPLE a consumer would never be aware the SAMPLE is no longer active and assume the SAMPLE at interval T=X was just missed or stopped working.  If no delete message was received for a SAMPLE at a certain interval, and no SAMPLE was received, it would signify the SAMPLE was missed or not properly reported.  Additional details are needed for clarification.

**Comment by gcsl** [comment]
Explicit deletion is always required to signify the removal of a leaf that is no longer present on a target device regardless of subscription mode, otherwise, as you suggest the existence could be ambiguous and indistinguishable from other types of faults. I would be supportive of updated wording that clarified this point.

Additionally, deletes are not required to be per-leaf and can be at an intermediate branch that applies to a multitude of leaves, e.g. when removing a logical interface in a configuration, deletes could be issued at container level branches that apply to that interface, rather than all the individual leaves.

**Comment by gwizdms** [comment]
We will work on a PR and submit soon for review.
