### ISSUE TITLE
broken import in proto/gnmi/gnmi.pb.go ?

### ISSUE THREAD

**Issue by little-dude** [openconfig/gnmi#39]
Hi,

My apologies if this report is not very clear, I'm not very familiar with either go or protobuf. But I'm trying to build a project which dependends on openconfig/gnmi, that started failing after https://github.com/openconfig/gnmi/commit/084de23686a4426d75b04f85bd51cc661a09a8c5

```
../../build/debug/third_party/go/src/github.com/openconfig/gnmi/proto/gnmi/gnmi.pb.go:22:8: no Go files in /build/debug/third_party/go/src/github.com/openconfig/gnmi/proto/gnmi_ext
```

It seems that [`openconfig/gnmi/proto/gnmi_ext`](https://github.com/openconfig/gnmi/tree/master/proto/gnmi_ext) does not contain any go file, so [this import fails](https://github.com/openconfig/gnmi/blob/084de23686a4426d75b04f85bd51cc661a09a8c5/proto/gnmi/gnmi.pb.go#L22) (at least that's my guess, but again, I don't know much about Go or this project in particular).

Thanks for your time.

**Comment by Pyro2266** [comment]
Hi,
I have very similar problem and I'm not good in go either. When I try to execute `go get -u github.com/google/gnxi/gnmi_get` command, I'm getting this error:
```
../../go/src/github.com/openconfig/gnmi/proto/gnmi/gnmi.pb.go:22:8: no buildable Go source files in /xxx/go/src/github.com/openconfig/gnmi/proto/gnmi_ext
```

This is clearly because of missing go files in gnmi_ext directory. They got deleted in this [commit](https://github.com/openconfig/gnmi/commit/084de23686a4426d75b04f85bd51cc661a09a8c5).

Was this intentional? If yes, how should I use 'go get' command, when [this](https://github.com/openconfig/gnmi/blob/master/proto/gnmi/gnmi.pb.go#L22) file is trying to import removed go files?

**Comment by gcsl** [comment]
Apologies.  The removal is not intentional but an artifact of the process
used to push out changes from our internal environment. Files have been
added back.

**Comment by little-dude** [comment]
Thank you @gcsl !
