### ISSUE TITLE
Question: about message Update/duplicates

### ISSUE THREAD

**Issue by moranxy** [openconfig/gnmi#65]
Hi,

I'm not sure how to use the filed duplicates in the message Update. 
can anybody describe some user scenarios?
thanks.

==
message Update {
  Path path = 1;                      // The path (key) for the update.
  Value value = 2 [deprecated=true];  // The value (value) for the update.
  TypedValue val = 3;                 // The explicitly typed update value.
  uint32 duplicates = 4;              // Number of coalesced duplicates.
}

**Comment by mkhsueh** [comment]
Hi @moranxy , duplicates is a counter value that indicates the number of coalesced duplicates. If a client is unable to keep up with the server, coalescion can occur on a per update (i.e., per path) basis such that the server can discard previous values for a given update and return only the latest. In this case the server should increment a count associated with the update such that a client can detect that transitions in the state of the path have occurred, but were suppressed due to its inability to keep up.
(see reference: https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-specification.md#21-reusable-notification-message-format)

Usage depends on your application scenario, e.g.:
One could determine when clients cannot keep up with telemetry updates and need performance tuning. It could also inform usage of gNMI data, or examining discrepancies in redundant monitoring job outputs.

**Comment by mkhsueh** [comment]
Any questions feel free to followup.
